<?php
/**
 * @file
 * Install, update and uninstall functions for the rh_bean module.
 *
 */


/**
 * Implements hook_update_last_removed().
 */
function rh_bean_update_last_removed() {
  return;
}

/**
 * Implements hook_update_N().
 */
function rh_bean_update_1000() {
  $config = config('rh_bean.settings');
}

/**
 * Implements hook_install().
 */
function rh_bean_install() {
  // Dynamically generated variable data was detected.
}
