<?php

/**
 * @file
 * Main module file for Rabbit Hole taxonomy terms module.
 *
 * This module will add the Rabbit Hole functionality to taxonomy terms.
 */

/**
 * Implements hook_rabbit_hole().
 */
function rh_taxonomy_rabbit_hole() {
  return array(
    'rh_taxonomy' => array(
      'entity type' => 'taxonomy_term',
      'base table' => 'taxonomy_term_data',
      'view path' => 'taxonomy/term/%/view',
    ),
  );
}

/**
 * Implements hook_config_info().
 */
function rh_taxonomy_config_info() {
  $prefixes['rh_taxonomy_term.settings'] = array(
    'label' => t('Taxonomy settings'),
    'group' => t('Rabbit Hole settings'),
  );
  return $prefixes;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * This will add Rabbit Hole options to the vocabulary form. These settings will
 * be used as default for every term of this vocabulary.
 */
function rh_taxonomy_form_taxonomy_form_vocabulary_alter(&$form, $form_state) {
  if (isset($form_state['confirm_delete'])) {
    // We're on the delete confirmation form.
    return;
  }

  // Add the Rabbit Hole form.
  rabbit_hole_form($form, 'taxonomy_term', $form['#vocabulary']->machine_name, 'rh_taxonomy');
  if (isset($form['rabbit_hole'])) {
    $form['rabbit_hole']['#attached']['js'][] = backdrop_get_path('module', 'rh_taxonomy') . '/rh-taxonomy.js';
  }
}

/**
 * Submit callback for the bundle form.
 *
 * This will set the values in the config file, and unset old values
 * if the machine name of the vocabulary has changed.
 */
function rh_taxonomy_bundle_form_submit($form, $form_state) {
  $config = config('rh_taxonomy_term.settings');
  $values = $form_state['values'];

  // Set the values in the config file. This will be set to the provided values,
  // if there are any provided values. They may be NULL if the user doesn't have
  // the administer rh_taxonomy permission. In this case, we'll set the
  // values according to the stored values for the old machine name. We'll
  // use the old machine name in case it has changed.
  $config->set('override_' . $values['machine_name'], isset($values['rh_taxonomy_term_override']) ? $values['rh_taxonomy_term_override'] : $config->get('override_' . $values['old_machine_name']));
  $config->set('action_' . $values['machine_name'], isset($values['rh_taxonomy_term_action']) ? $values['rh_taxonomy_term_action'] : $config->get('action_' . $values['old_machine_name']));
  $config->set('redirect_' . $values['machine_name'], isset($values['rh_taxonomy_term_redirect']) ? $values['rh_taxonomy_term_redirect'] : $config->get('redirect_' . $values['old_machine_name']));
  $config->set('redirect_response_' . $values['machine_name'], isset($values['rh_taxonomy_term_redirect_response']) ? $values['rh_taxonomy_term_redirect_response'] : $config->get('redirect_response_' . $values['old_machine_name']));
  $config->save();

  // Clear old config values if the machine name has changed.
  if (isset($values['old_machine_name']) && $values['machine_name'] != $values['old_machine_name']) {
    rabbit_hole_clear_config_values('taxonomy_term', $values['old_machine_name']);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * This will add Rabbit Hole options to the taxonomy term form. The user will
 * be able to override the default Rabbit Hole options.
 */
function rh_taxonomy_form_taxonomy_form_term_alter(&$form, $form_state) {
  if (isset($form_state['confirm_delete'])) {
    // We're on the delete confirmation form.
    return;
  }

  // Add the Rabbit Hole form.
  rabbit_hole_form($form, 'taxonomy_term', $form['#bundle'], 'rh_taxonomy', (object) $form['#term']);
}

/**
 * Implements hook_taxonomy_term_view().
 */
function rh_taxonomy_taxonomy_term_view($term, $view_mode, $langcode) {
  // Execute Rabbit Hole, if the term is being viewed at its own page using the
  // full view mode, and the current user isn't able to override Rabbit Hole.
  if ($view_mode == 'full' && taxonomy_term_is_page($term) && !user_access('bypass rh_taxonomy')) {
    rabbit_hole_execute('taxonomy_term', $term);
  }
}

/**
 * Implements hook_views_pre_build().
 */
function rh_taxonomy_views_pre_build(&$view) {
  // Execute Rabbit Hole, if the term is being viewed using the "Taxonomy Term"
  // view, and the current user isn't able to override Rabbit Hole.
  if ($view->name == 'taxonomy_term' && !user_access('bypass rh_taxonomy')) {
    $tid = $view->args[0];
    $term = taxonomy_term_load($tid);
    rabbit_hole_execute('taxonomy_term', $term);
  }
}

/**
 * Implements hook_taxonomy_vocabulary_delete().
 */
function rh_taxonomy_taxonomy_vocabulary_delete($vocabulary) {
  // Clear config values connected to this vocabulary.
  rabbit_hole_clear_config_values('taxonomy_term', $vocabulary->machine_name);
}
