<?php
/**
 * @file
 * Install, update and uninstall functions for the rh_field_collection module.
 *
 */


/**
 * Implements hook_update_last_removed().
 */
function rh_field_collection_update_last_removed() {
  return;
}

/**
 * Implements hook_update_N().
 */
function rh_field_collection_update_1000() {
  $config = config('rh_field_collection.settings');
}

/**
 * Implements hook_install().
 */
function rh_field_collection_install() {
  // Dynamically generated variable data was detected.
}
